<?php


namespace App\Admin\Content\HighTypes;


class TextProvider extends HighTypeProvider
{

    protected function getFormType($name, $type, $options = [])
    {
        return parent::getFormType($name, $type, $options); // TODO: Change the autogenerated stub
    }

}
